#! /bin/sh
### BEGIN INIT INFO
# Provides:          Alfred
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts & Stops Alfred
### END INIT INFO
#Switch case fuer den ersten Parameter
case "$1" in
    start)
 #Aktion wenn start uebergeben wird
        echo "Starte Alfred"
        cd /home/pi/Alfred
        ./Alf_Start.sh
     
    stop)
 #Aktion wenn stop uebergeben wird
        echo "Stoppe Alfred"
        cd /home/pi/Alfred
        ./Alf_Stop.sh
 
    restart)
 #Aktion wenn restart uebergeben wird
        echo "Restarte Alfred"
        cd /home/pi/Alfred
        ./Alf_Stop.sh
        sleep 2
        ./Alf_Start.sh
 
    update)
#Aktion wenn update uebergeben wird
        echo "Update Alfred"
        cd /home/pi/Alfred
        ./Alf_Update.sh
 *)
 #Standard Aktion wenn start|stop|restart nicht passen
 echo "(start|stop|restart)"
 
esac
exit 0
